### ISSUE TITLE
CURLOPT_FOLLOWLOCATION and safe mode

### ISSUE THREAD

**Issue by DanielRuf** [bastianallgeier/kirby-webmentions#7]
On websites with enabled safe mode, especially managed hosting, CURLOPT_FOLLOWLOCATION can not be used and throws an exception.

We have to use a workaround or just comment out the line in /vendor/mf2.php.

**Comment by sebsel** [comment]
One workaround could be to use `remote::get()` from the Kirby Toolkit in combination with `\Mf2\parse($html)` instead of `\Mf2\fetch($src)`, but Kirby Toolkit has it set `true` by default also.

**Comment by DanielRuf** [comment]
Bump.
