### ISSUE TITLE
Please license

### ISSUE THREAD

**Issue by sebsel** [bastianallgeier/kirby-webmentions#8]
I started using your plugin, and then I needed it to do some more, so I forked. And that grew. And now people are using my fork. But... I realise that this repo is not licensed, so I don't actually know what I can and can not do.

Would you mind to add one? Thanks!

**Comment by sebastiangreger** [comment]
:+1: I'd love to reuse parts for a potential Kirby 3 implementation. Thanks!

**Comment by bastianallgeier** [comment]
I'm so sorry that it took so long. I just added the MIT license.
