### ISSUE TITLE
pings.json empty

### ISSUE THREAD

**Issue by AlexKucera** [bastianallgeier/kirby-webmentions#9]
I installed the plugin and made the https://webmention.rocks Endpoint discovery test post. (http://blog.alexanderkucera.com/microblog/snippet_webmention_test)

The plugin does create the .webmentions folder and inside the pings.json file. However, the file only contains `[]` and hence no web mentions get sent. Can I debug this somehow on my end? 

The links for this test post are as simple Markdown/HTML document:

```
Title: —

----

Text: Testing Webmentions with Kirby's <a href="https://github.com/bastianallgeier/kirby-webmentions">Webmention plugin</a>. Probably not going to work. Let's see…
<a href="https://webmention.rocks/test/1">Test 1</a>
…
…
…
<a href="https://webmention.rocks/test/22">Test 22</a>
<a href="https://webmention.rocks/test/23/page">Test 23</a>

----

Date: 29.06.2017

----

Time: 2017-06-29-14-29-36
```

**Comment by sebsel** [comment]
Did you visit the page before you added the links? If so, delete the pings.json to try sending them again :)

**Comment by AlexKucera** [comment]
Yes. I did. But I also already tried deleting the JSON file. It recreated it in the same empty manner.  

--  
Alexander Kucera  

Von: Sebastiaan Andeweg <notifications@github.com>(mailto:notifications@github.com)
Antworten: bastianallgeier/kirby-webmentions <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 29. Juni 2017 at 15:59:12
An: bastianallgeier/kirby-webmentions <kirby-webmentions@noreply.github.com>(mailto:kirby-webmentions@noreply.github.com)
CC: Alexander Kucera <a.kucera@babylondreams.de>(mailto:a.kucera@babylondreams.de), Author <author@noreply.github.com>(mailto:author@noreply.github.com)
Betreff: Re: [bastianallgeier/kirby-webmentions] pings.json empty (#9)

**Comment by sebsel** [comment]
Oh, I remember: the regex did not understand .rocks
https://github.com/sebsel/seblog-kirby-webmentions/commit/8890970d5a5139ac9e21e070c2a04b2bf4199190

[My version of the plugin](https://github.com/sebsel/seblog-kirby-webmentions) will also not pass all the tests btw, because it relies on this PR, which is not merged into the toolkit. I should probably move that code to my plugin then.
https://github.com/getkirby/toolkit/pull/213

**Comment by AlexKucera** [comment]
Thanks. I'll give your version a try.

**Comment by AlexKucera** [comment]
That seems to work. Thanks again.
